version: '3.8'

services:
#  postgres:
#    image: postgres:16
#    container_name: postgres-db
#    environment:
#      POSTGRES_DB: basketball
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: java-app
    ports:
      - "8080:8080"
    volumes:
      - .:/java-app
      - ~/.m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  frontend:
    build:
      context: ../frontend-java
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5173:5173"
    volumes:
      - ../frontend-java:/frontend-java       # match WORKDIR in Dockerfile
      - /frontend-java/node_modules          # preserve container node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true             # needed for Vite hot reload in Docker
    depends_on:
      - app

volumes:
  postgres-data: